global:
  scrape_interval: 1s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "orderer"
    static_configs:
      - targets: ["orderer.pnu.cse:9443"]
  - job_name: "peer0_seller"
    static_configs:
      - targets: ["peer0.seller.pnu.cse:9444"]
  - job_name: "peer0_buyer"
    static_configs:
      - targets: ["peer0.buyer.pnu.cse:9445"]
  - job_name: "peer0_inspector"
    static_configs:
      - targets: ["peer0.inspector.pnu.cse:9446"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']
