apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: {{ .Values.global.namespace }}
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repoURL }}
    targetRevision: argocd
    path: gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
