server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    probes:
      enabled: true

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:3001"
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
      routes:
        - id: signup-service
          uri: http://auth:8080
          predicates:
            - Path=/sign-up/**
        - id: auth-service-post
          uri: http://auth:8080
          predicates:
            - Path=/auth/**
            - Method=POST, OPTIONS
        - id: auth-service
          uri: http://auth:8080
          predicates:
            - Path=/auth/**
            - Method= DELETE, GET, PATCH
          filters:
            - AuthorizationHeaderFilter
        - id: review-service
          uri: http://review:8080
          predicates:
            - Path=/review/**
          filters:
            - AuthorizationHeaderFilter
        - id: contract-service-get-contract
          uri: http://contract:8080
          predicates:
            - Path=/contract/get-contract
        - id: contract-service
          uri: http://contract:8080
          predicates:
            - Path=/contract/**
          filters:
            - AuthorizationHeaderFilter
        - id: carinfo-service-get
          uri: http://carinfo:8080
          predicates:
            - Path=/car-info/**
            - Method= GET
        - id: carinfo-service
          uri: http://carinfo:8080
          predicates:
            - Path=/car-info/**
            - Method= POST, PATCH, PUT, OPTIONS
          filters:
            - AuthorizationHeaderFilter

token:
  access_expired_time: 3600000
  secret_key: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  refresh_expired_time: 3600000
