version: '2'
services:
  postgres:
    container_name: postgres
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cluster
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data