name: cloudchainCI

on:
  push:
    branches: 
      - main
  workflow_dispatch: 

env:
  git_tag: ${{ github.sha }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, carinfo, contract, gateway, review]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Changed Directories
        id: get-changed-dir
        run: |
          changed_folders=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '/.*' | awk 'BEGIN {FS="/"} {print $1}' | sort -u)
          echo "Changed folders: $changed_folders"
          echo "::set-output name=folders::$changed_folders"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cloudchain-${{ matrix.service }}:latest
        if: github.event_name == 'workflow_dispatch' || contains(steps.get-changed-dir.outputs.folders, matrix.service)

  update-argocd-manifest:
    needs: build_and_push
    runs-on: ubuntu-20.04
    
    defaults:
      run:
        working-directory: ./signup/

    steps:
    - name: Checkout argocd-deploy branch
      uses: actions/checkout@v3
      with:
        ref: cloudchain
        token: ${{ secrets.CLOUDCHAIN_PRIVATE }}

    - name: Change image-tag.yaml
      run: |
        cat <<EOF > image-tag.yaml
        image:
          tag: ${{ env.git_tag }}
        EOF

    - name: New git tag push
      run: |
        git config --global user.email "GitHub Actions Bot@github.com"
        git config --global user.name "GitHub Actions Bot"
        git add image-tag.yaml
        git commit -m "update git tag"
        git pull origin cloudchain
        git push origin cloudchain

      
