# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

volumes:
  orderer.pnu.cse:
  peer0.seller.pnu.cse:
  peer0.buyer.pnu.cse:
  peer0.inspector.pnu.cse:
  peer1.seller.pnu.cse:
  peer1.buyer.pnu.cse:
  peer1.inspector.pnu.cse:

networks:
  test:
    name: fabric_test

services:

  orderer.pnu.cse:
    container_name: orderer.pnu.cse
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.pnu.cse:9443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
        - ../organizations/ordererOrganizations/pnu.cse/orderers/orderer.pnu.cse/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/pnu.cse/orderers/orderer.pnu.cse/tls/:/var/hyperledger/orderer/tls
        - orderer.pnu.cse:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - test

  peer0.seller.pnu.cse:
    container_name: peer0.seller.pnu.cse
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.seller.pnu.cse
      - CORE_PEER_ADDRESS=peer0.seller.pnu.cse:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.seller.pnu.cse:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.seller.pnu.cse:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.seller.pnu.cse:7051
      - CORE_PEER_LOCALMSPID=sellerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.seller.pnu.cse:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0seller"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
        - ../organizations/peerOrganizations/seller.pnu.cse/peers/peer0.seller.pnu.cse:/etc/hyperledger/fabric
        - peer0.seller.pnu.cse:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 7051:7051
      - 9444:9444
    networks:
      - test

  peer0.buyer.pnu.cse:
    container_name: peer0.buyer.pnu.cse
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.buyer.pnu.cse
      - CORE_PEER_ADDRESS=peer0.buyer.pnu.cse:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.buyer.pnu.cse:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.buyer.pnu.cse:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.buyer.pnu.cse:9051
      - CORE_PEER_LOCALMSPID=buyerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp      
      - CORE_OPERATIONS_LISTENADDRESS=peer0.buyer.pnu.cse:9445
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0buyer"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
        - ../organizations/peerOrganizations/buyer.pnu.cse/peers/peer0.buyer.pnu.cse:/etc/hyperledger/fabric
        - peer0.buyer.pnu.cse:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 9051:9051
      - 9445:9445
    networks:
      - test


# peer3
  peer0.inspector.pnu.cse:
    container_name: peer0.inspector.pnu.cse
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      #Generic peer variables
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.inspector.pnu.cse
      - CORE_PEER_ADDRESS=peer0.inspector.pnu.cse:11051
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.inspector.pnu.cse:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.inspector.pnu.cse:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.inspector.pnu.cse:11051
      - CORE_PEER_LOCALMSPID=inspectorMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.inspector.pnu.cse:9446
      - CORE_METRICS_PROVIDER=prometheus
      #이부분 바꿈 peerOseller -> peerOinspector
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0inspector"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s      
    volumes:
        - ../organizations/peerOrganizations/inspector.pnu.cse/peers/peer0.inspector.pnu.cse:/etc/hyperledger/fabric        
        - peer0.inspector.pnu.cse:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 11051:11051
      - 9446:9446
    networks:
      - test

  peer1.seller.pnu.cse:
    container_name: peer1.seller.pnu.cse
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.seller.pnu.cse
      - CORE_PEER_ADDRESS=peer1.seller.pnu.cse:7151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7151
      - CORE_PEER_CHAINCODEADDRESS=peer1.seller.pnu.cse:7152
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7152
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.seller.pnu.cse:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.seller.pnu.cse:7151
      - CORE_PEER_LOCALMSPID=sellerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer1.seller.pnu.cse:9447
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1seller"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
        - ../organizations/peerOrganizations/seller.pnu.cse/peers/peer1.seller.pnu.cse:/etc/hyperledger/fabric
        - peer1.seller.pnu.cse:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 7151:7151
      - 9447:9447
    networks:
      - test

  peer1.buyer.pnu.cse:
    container_name: peer1.buyer.pnu.cse
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.buyer.pnu.cse
      - CORE_PEER_ADDRESS=peer1.buyer.pnu.cse:9151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9151
      - CORE_PEER_CHAINCODEADDRESS=peer1.buyer.pnu.cse:9152
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9152
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.buyer.pnu.cse:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.buyer.pnu.cse:9151
      - CORE_PEER_LOCALMSPID=buyerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp      
      - CORE_OPERATIONS_LISTENADDRESS=peer1.buyer.pnu.cse:9448
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1buyer"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
        - ../organizations/peerOrganizations/buyer.pnu.cse/peers/peer1.buyer.pnu.cse:/etc/hyperledger/fabric
        - peer1.buyer.pnu.cse:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 9151:9151
      - 9448:9448
    networks:
      - test

# peer3
  peer1.inspector.pnu.cse:
    container_name: peer1.inspector.pnu.cse
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.inspector.pnu.cse
      - CORE_PEER_ADDRESS=peer1.inspector.pnu.cse:11151
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11151
      - CORE_PEER_CHAINCODEADDRESS=peer1.inspector.pnu.cse:11152
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11152
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.inspector.pnu.cse:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.inspector.pnu.cse:11151
      - CORE_PEER_LOCALMSPID=inspectorMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer1.inspector.pnu.cse:9449
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1inspector"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s      
    volumes:
        - ../organizations/peerOrganizations/inspector.pnu.cse/peers/peer1.inspector.pnu.cse:/etc/hyperledger/fabric        
        - peer1.inspector.pnu.cse:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 11151:11151
      - 9449:9449
    networks:
      - test


  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.seller.pnu.cse
      - peer0.buyer.pnu.cse
      - peer0.inspector.pnu.cse
    networks:
      - test
